# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vehicular Intelligence Lab
short_labname: VIL
email: physi5logy@gmail.com
logo: logo3.png
description: > # 다음 줄에 연구실 소개 입력
  VILlab of CCS School of Mobility, Korea Advanced Institute of Science and Technology; KAIST 조천식모빌리티대학원 하동수 교수 연구실; Dongsoo Har;
baseurl: "" # the subpath of your site, e.g. /blog
github_username: VIL
google-site-verification:

# Build settings
markdown: kramdown
include: ["_pages", "_news"]
plugins: [jekyll-seo-tag, jekyll-paginate]

paginate: 5
paginate_path: "/news/page:num/"
