name: Synchronize to forked repo
on:
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.FORKED_REPO_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://KAIST-VIL:${{ secrets.FORKED_REPO_TOKEN }}@github.com/KAIST-VIL/kaist-vil.github.io
          git config user.name SeungAhSon
          git config user.email gongsoonyee@gmail.com
      
      - name: Push changes to forked-repo 
        run: |
          git push -f forked-repo main
      
      - name: Clean up
        run: |
          git remote remove forked-repo
