name: Synchronize to forked repo
on:
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync SeungAhSon repo to kaist-vil.github.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.MY_REPO_TOKEN }}
          fetch-depth: 0
          ref: master

      - name: Add remote URL for KAIST-VIL repo
        run: |
          git remote add kaist-vil https://KAIST-VIL:${{ secrets.MY_REPO_TOKEN }}@github.com/KAIST-VIL/kaist-vil.github.io
          git config user.name SeungAhSon
          git config user.email gongsoonyee@gmail.com
      
      - name: Push changes to kaist-vil.github.io repo
        run: |
          git push -f kaist-vil master
      
      - name: Clean up remote
        run: |
          git remote remove kaist-vil
